dist: focal # Ubuntu 20.04 LTS
language: ruby

cache:
  - apt
  - bundler

rvm:
  - 3.0.0

env:
  global:
    - SERVICE_NAME=dummy_project
    - RUBYGEMS_VERSION=3.2.15
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_VERSION=5.7.33
    - DB_PASSWORD=db_password
    - CI=true
    - BUNDLE_PATH=vendor/cache

git:
  depth: 1

services:
  - docker

before_install:
  - gem update --system 3.2.27
  - nvm install v14.17.2
  - nvm use v14.17.2

install:
  - bundle config set --local deployment 'true'
  - |
    BUNDLE_WITHOUT=production \
    BUNDLE_JOBS=3 \
    BUNDLE_RETRY=3 \
    BUNDLE_PATH=vendor/cache \
    bundler install --local

before_script:
  - |
    docker run --rm --detach \
      --env MYSQL_ROOT_PASSWORD=${DB_PASSWORD} \
      --network=host \
      mysql:${DB_VERSION}

  - |
    docker build . \
      --build-arg ARG_COMPOSE_WAIT_VER=${ARG_COMPOSE_WAIT_VER} \
      --tag ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER} \
      -f dockerfiles/Dockerfile.wait

  - |
    docker run --rm \
      --env WAIT_HOSTS=127.0.0.1:3306 \
      --network=host \
      ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER}

  - |
    DB_HOST=127.0.0.1 \
    DB_PORT=3306 \
    BUNDLE_PATH=vendor/cache \
    CI=true \
    bin/rails db:setup

  - |
    DB_HOST=127.0.0.1 \
    DB_PORT=3306 \
    BUNDLE_PATH=vendor/cache \
    CI=true \
    bin/rails webpacker:install

jobs:
  include:
    - stage: Application correctness
      script: |
        DB_HOST=127.0.0.1 \
        DB_PORT=3306 \
        BUNDLE_PATH=vendor/cache \
        CI=true \
        bin/rails test:db
      name: Test suite