dist: focal # Ubuntu 20.04 LTS
language: ruby

cache:
  - apt
  - bundler

rvm:
  - 3.0.0

env:
  global:
    - SERVICE_NAME=dummy_project
    - BUNDLE_PATH=vendor/cache
    - BUNDLE_WITHOUT=production
    - BUNDLE_JOBS=3
    - BUNDLE_RETRY=3
    - BUNDLE_PATH=vendor/cache
    - BUNDLE_VERSION=2.2.27
    - RUBYGEMS_VERSION=3.2.27
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_PORT=3333
    - DB_VERSION=5.7.33

git:
  depth: 1

before_install:
  - gem update --system 3.2.27

install:
  - bundle config set --local deployment 'true'
  - BUNDLE_PATH=vendor/cache bundler install --local

before_script:
  - docker run --rm --detach --name dummy_project-db --env MYSQL_ROOT_PASSWORD=root --publish 3333:3306 mysql:5.7.33
  - docker build . --build-arg ARG_COMPOSE_WAIT_VER=2.9.0 --tag dummy_project/wait:2.9.0 -f dockerfiles/Dockerfile.wait
  - docker run --rm --name dummy_project-wait --env WAIT_HOSTS=127.0.0.1:3333 dummy_project/wait:2.9.0
  - bin/rails db:setup

jobs:
  include:
    - stage: Application correctness
      script: bin/rails test:db
      name: Test suite