dist: focal # Ubuntu 20.04 LTS
language: ruby

# cache:
#   - apt
#   - bundler

rvm:
  - 3.0.0

env:
  global:
    - SERVICE_NAME=dummy_project
    - BUNDLE_PATH=vendor/cache
    - BUNDLE_WITHOUT=production
    - BUNDLE_JOBS=3
    - BUNDLE_RETRY=3
    - BUNDLE_PATH=vendor/cache
    - BUNDLE_VERSION=2.2.27
    - RUBYGEMS_VERSION=3.2.27
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_PORT=3306
    - DB_VERSION=5.7.33
    - CI

git:
  depth: 1

services:
  - docker

before_install:
  - gem update --system 3.2.27

install:
  - bundle config set --local deployment 'true'
  - BUNDLE_PATH=vendor/cache bundler install --local

before_script:
  - docker run --rm --detach --name ${SERVICE_NAME}-db --env MYSQL_ROOT_PASSWORD=root --network=host mysql:${DB_VERSION}
  - docker build . --build-arg ARG_COMPOSE_WAIT_VER=2.9.0 --tag dummy_project/wait:2.9.0 -f dockerfiles/Dockerfile.wait
  - docker run --rm --name dummy_project-wait --env WAIT_HOSTS=127.0.0.1:3306 --network=host dummy_project/wait:2.9.0
  - bundle exec rails db:setup

jobs:
  include:
    - stage: Application correctness
      script: bundle exec rails test:db
      name: Test suite